name: Test and Lint 

on:
    workflow_call:
        secrets:
            DOCKERHUB_USER:
                required: true
                description: "username for dockerhub auth"
            DOCKERHUB_TOKEN:
                required: true
                description: "token for dockerhub auth "
jobs:
    python:
        name: Python
        runs-on: ubuntu-22.04
        steps:
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USER}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: code checkout
              uses: actions/checkout@v4
            - name: run python test
              run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: python flake8 
              run: docker compose run --rm app sh -c "flake8"